name: __packages__
on:
  workflow_call:
    inputs:
      BOARD:
        required: true
        type: string
    secrets:
      DEPLOY_KEY:
        required: true


jobs:
  packages:
    runs-on: ubuntu-latest
    env:
      DEPLOY_KEY: "${{secrets.DEPLOY_KEY}}"
      BOARD: "${{inputs.BOARD}}"
      TERM: xterm
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configuring SSH
        run: |
          test -n "$DEPLOY_KEY"
          mkdir ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -H files.pikvm.org > ~/.ssh/known_hosts
          echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Fetching current repo
        run: |
          make download DEPLOY_USER=data

      - name: Building environment
        run: make buildenv BOARD=$BOARD NC=1

      - name: Building packages
        run: make _build BOARD=$BOARD PKG=kvmd NOINT=1 NOSIGN=1 FORCE=1
